### ISSUE TITLE
dam-koto is not working while browsing 

### ISSUE THREAD

**Issue by fazlerabbi37** [itskhaledmohammad/dam-koto-chrome#3]
I opened [amazon.com](amazon.com) and went over the *Today's Deals* section to browse some product. But unfortunately the extension was not working. It didn't work until I went to that specific product page.

**Comment by itskhaledmohammad** [comment]
Dam Koto 3.1.2 has been shipped, I have fixed the issue with amazon's "Today's Deal". Thanks for letting me know the issue.
